services:
  - type: web
    name: ai-image-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: ZHIPU_API_KEY  
        sync: false
      - key: JWT_SECRET
        sync: false 